### ISSUE TITLE
appimage dont work - Linux Mint 20.0

### ISSUE THREAD

**Issue by nicodoo76** [AppsusUK/NFT-Art-Generator#1]
appimage dont start with linux mint 20. try version 0.0.2 and 0.0.3

also try right clic on file and give permission Allow executing file as program. Dont work. 

Thanks for fix !

**Comment by AppsusUK** [comment]
Hi, thanks for posting our first issue! I've only tested on Ubuntu 20.04 LTS and it works fine there. I'll take a look into on mint 20 and update here

**Comment by nicodoo76** [comment]
Hello and thanks for your fast replay...

hmmm.... just checked: Linux Mint 20.0 also on Ubuntu 20.04 basis.

I get no error message when try to open. Same when try to open in
terminal...

**Comment by AbdulDridi** [comment]
Hey Nico, could you try running this AppImage on ubuntu again? 
I just rebuilt the Linux AppImage as I suspect it may have been corrupted in some form, and was also having issues with it
https://github.com/AppsusUK/NFT-Art-Generator/releases/download/v0.0.3/Appsus.NFT.Art.Generator.AppImage

It it still doesn't work, could you please upload the log you get from running this command:
`strace ./Appsus.NFT.Art.Generator.AppImage 2&>1`

With regards to Linux Mint, since this is an Electron App, perhaps the advice here could be relevant?
https://docs.appimage.org/user-guide/troubleshooting/electron-sandboxing.html

I'd try that after testing the new image, since I had issues with that one too (version 0.0.2 should still have worked though)

**Comment by nicodoo76** [comment]
Now working perfect. Thank you a lot. p.s.: I use Linux Mint 64 bit

**Comment by AbdulDridi** [comment]
All good, happy to help! :smile:
